
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int INT = 2;
  public static final int IDENT = 12;
  public static final int FLOATCONST = 11;
  public static final int PLUS = 9;
  public static final int EOF = 0;
  public static final int ASSIGN = 8;
  public static final int error = 1;
  public static final int PRINT = 4;
  public static final int SEMICOLON = 5;
  public static final int RPAREN = 7;
  public static final int INTCONST = 10;
  public static final int LPAREN = 6;
  public static final int FLOAT = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "PRINT",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "ASSIGN",
  "PLUS",
  "INTCONST",
  "FLOATCONST",
  "IDENT"
  };
}

