
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int AND = 27;
  public static final int NE = 25;
  public static final int LT = 23;
  public static final int IDENT = 32;
  public static final int SEMICOLON = 10;
  public static final int ELSE = 6;
  public static final int PLUS = 16;
  public static final int OR = 28;
  public static final int RPAREN = 12;
  public static final int INT = 2;
  public static final int WHILE = 7;
  public static final int NOT = 29;
  public static final int END = 14;
  public static final int INTCONST = 30;
  public static final int IF = 5;
  public static final int GT = 24;
  public static final int LPAREN = 11;
  public static final int LE = 21;
  public static final int READFLOAT = 9;
  public static final int BEGIN = 13;
  public static final int FLOAT = 3;
  public static final int EOF = 0;
  public static final int DIV = 19;
  public static final int GE = 22;
  public static final int MINUS = 17;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int EQ = 26;
  public static final int ASSIGN = 15;
  public static final int FLOATCONST = 31;
  public static final int READINT = 8;
  public static final int UMINUS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "PRINT",
  "IF",
  "ELSE",
  "WHILE",
  "READINT",
  "READFLOAT",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "BEGIN",
  "END",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "LE",
  "GE",
  "LT",
  "GT",
  "NE",
  "EQ",
  "AND",
  "OR",
  "NOT",
  "INTCONST",
  "FLOATCONST",
  "IDENT"
  };
}

